# Generated by Django 5.2.10 on 2026-01-31 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('xp_per_level', models.PositiveIntegerField(default=100, help_text='XP needed per level')),
                ('max_level', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'season',
                'verbose_name_plural': 'seasons',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('milestone', 'Milestone')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target', models.PositiveIntegerField(default=1, help_text="Target count to complete (e.g. 5 for 'Attend 5 events')")),
                ('xp_reward', models.PositiveIntegerField(default=25)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='season.season')),
            ],
            options={
                'verbose_name': 'quest',
                'verbose_name_plural': 'quests',
                'ordering': ['season', 'quest_type', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SeasonReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(help_text='Level 1-10')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('reward_type', models.CharField(choices=[('xp', 'XP Bonus'), ('cosmetic', 'Cosmetic'), ('badge', 'Badge'), ('title', 'Title'), ('other', 'Other')], default='other', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon name', max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='season.season')),
            ],
            options={
                'verbose_name': 'season reward',
                'verbose_name_plural': 'season rewards',
                'ordering': ['season', 'level'],
                'unique_together': {('season', 'level')},
            },
        ),
        migrations.CreateModel(
            name='UserQuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='season.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user quest progress',
                'verbose_name_plural': 'user quest progresses',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'quest')},
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('season_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='season.seasonreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user reward',
                'verbose_name_plural': 'user rewards',
                'ordering': ['-claimed_at'],
                'unique_together': {('user', 'season_reward')},
            },
        ),
    ]
