# Generated by Django 5.2.10 on 2026-01-31 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shanyraq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('shanyraq_leader', 'Shanyraq Leader'), ('student_council', 'Student Council'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=20),
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('class_name', models.CharField(blank=True, help_text='e.g. 10A, 11B', max_length=64)),
                ('NIS_points', models.PositiveIntegerField(default=0)),
                ('shanyraq_points', models.PositiveIntegerField(default=0)),
                ('rank', models.CharField(blank=True, help_text='e.g. Bronze, Silver, Gold', max_length=64)),
                ('shanyraq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='shanyraq.shanyraq')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
