# Generated by Django 5.2.10 on 2026-01-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_onboarding_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_score',
            field=models.PositiveIntegerField(default=0, help_text='Cached activity metric'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, help_text='Comma-separated interests'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
