# Generated by Django 5.2.10 on 2026-02-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_bio_userprofile_github_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='NIS_points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shanyraq_points',
        ),
        migrations.AddField(
            model_name='user',
            name='lifetime_xp',
            field=models.PositiveIntegerField(default=0, help_text='Total XP earned all time'),
        ),
        migrations.AddField(
            model_name='user',
            name='season_xp',
            field=models.PositiveIntegerField(default=0, help_text='XP earned this season'),
        ),
    ]
