# Generated by Django 5.2.10 on 2026-02-01 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_userprofile_nis_points_and_more"),
        ("shanyraq", "0003_remove_shanyraq_total_points_shanyraq_lifetime_sp_and_more"),
    ]

    operations = [
        # Data migration is not needed since the schema migration already handled the data
    ]
