# Generated by Django 5.2.10 on 2026-01-31 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'opportunity tag',
                'verbose_name_plural': 'opportunity tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(choices=[('olympiad', 'Olympiad'), ('project', 'Project'), ('competition', 'Competition'), ('program', 'Program'), ('other', 'Other')], default='other', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='e.g. Mathematics, Physics', max_length=128)),
                ('description', models.TextField(blank=True)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, help_text='External link for more info')),
                ('prep_checklist', models.TextField(blank=True, help_text='One item per line: prepare documents, register online, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='opportunities', to='opportunities.opportunitytag')),
            ],
            options={
                'verbose_name': 'opportunity',
                'verbose_name_plural': 'opportunities',
                'ordering': ['-deadline', '-created_at'],
            },
        ),
    ]
