# Generated by Django 5.2.10 on 2026-01-31 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve_event', 'Approve Event'), ('reject_event', 'Reject Event'), ('approve_booking', 'Approve Space Booking'), ('reject_booking', 'Reject Space Booking'), ('cancel_booking', 'Cancel Space Booking'), ('add_points', 'Add Points'), ('revoke_points', 'Revoke Points'), ('update_user', 'Update User'), ('update_shanyraq', 'Update Shanyraq')], max_length=20)),
                ('target_model', models.CharField(help_text="Model name (e.g. 'events.Event')", max_length=100)),
                ('target_id', models.PositiveIntegerField(help_text='Primary key of the target object')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('old_value', models.TextField(blank=True, help_text='JSON representation of old state')),
                ('new_value', models.TextField(blank=True, help_text='JSON representation of new state')),
                ('comment', models.TextField(blank=True, help_text='Optional moderator comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'moderator action log',
                'verbose_name_plural': 'moderator action logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='moderation__action__218bf7_idx'), models.Index(fields=['moderator', 'created_at'], name='moderation__moderat_71e95c_idx')],
            },
        ),
    ]
