# Generated by Django 5.2.10 on 2026-01-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shanyraq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Shanyraq',
                'verbose_name_plural': 'Shanyraqs',
                'ordering': ['name'],
            },
        ),
    ]
