# Generated by Django 5.2.10 on 2026-01-31 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shanyraq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shanyraq',
            name='total_points',
            field=models.PositiveIntegerField(default=0, help_text='Cached sum of member shanyraq_points'),
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive = credit, negative = debit/penalty')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('event', 'Event'), ('activity', 'Activity'), ('admin', 'Admin'), ('penalty', 'Penalty')], default='admin', max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, help_text='PK of event/activity etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL)),
                ('shanyraq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='shanyraq.shanyraq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point transaction',
                'verbose_name_plural': 'Point transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShanyraqMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('shanyraq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='shanyraq.shanyraq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shanyraq_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shanyraq membership',
                'verbose_name_plural': 'Shanyraq memberships',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'shanyraq')},
            },
        ),
    ]
