# Generated by Django 5.2.10 on 2026-02-01 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shanyraq', '0002_add_membership_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shanyraq',
            name='total_points',
        ),
        migrations.AddField(
            model_name='shanyraq',
            name='lifetime_sp',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime Shanyraq Points (cached sum of member lifetime_xp)'),
        ),
        migrations.AddField(
            model_name='shanyraq',
            name='season_sp',
            field=models.PositiveIntegerField(default=0, help_text='Season Shanyraq Points (cached sum of member season_xp)'),
        ),
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('awards_xp', models.PositiveIntegerField(default=0, help_text='XP awarded for this activity')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity submission',
                'verbose_name_plural': 'Activity submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='XPLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_xp', models.IntegerField(help_text='XP change amount (positive = credit, negative = debit/penalty)')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('event', 'Event'), ('activity', 'Activity'), ('admin', 'Admin'), ('penalty', 'Penalty')], default='admin', max_length=20)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='PK of event/activity etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_xp_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XP transaction',
                'verbose_name_plural': 'XP transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PointTransaction',
        ),
    ]
