# Generated by Django 5.2.10 on 2026-01-31 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('space_type', models.CharField(choices=[('classroom', 'Classroom'), ('auditorium', 'Auditorium'), ('lab', 'Lab'), ('conference', 'Conference Room'), ('sports', 'Sports Facility'), ('other', 'Other')], default='other', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Maximum number of people')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Building/floor/room number', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'space',
                'verbose_name_plural': 'spaces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purpose', models.TextField(blank=True, help_text='Purpose of booking')),
                ('attendees_count', models.PositiveIntegerField(default=1, help_text='Expected number of attendees')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_bookings', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bookings', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='spaces.space')),
            ],
            options={
                'verbose_name': 'space booking',
                'verbose_name_plural': 'space bookings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_approval_actions', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='spaces.spacebooking')),
            ],
            options={
                'verbose_name': 'booking approval log',
                'verbose_name_plural': 'booking approval logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='spacebooking',
            index=models.Index(fields=['space', 'start_time', 'end_time'], name='spaces_spac_space_i_ffcee8_idx'),
        ),
        migrations.AddIndex(
            model_name='spacebooking',
            index=models.Index(fields=['status', 'start_time'], name='spaces_spac_status_5fba76_idx'),
        ),
    ]
